name: Pack
on:
  push:
    branches: [lib]
  workflow_dispatch:
env:
  BUILD: Travel Earth Plan
  VERSION: Build Edition


jobs:
  CreateCursePack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run runner/build.sh
        run: bash runner/build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD }} - ${{ env.VERSION }} v${{ github.run_number }}
          path: artifacts
